Submission library file upload validation
pkp/controlPublicFiles pull request #14
Opened 2023-09-15 18:08 UTC by MrRob100

Submission library file upload filetypes restricted to those declared in the plugin's settings.
![Screenshot 2023-09-15 at 13 53 23](https://github.com/pkp/controlPublicFiles/assets/43947674/98070032-25f0-4332-9e1a-61ca29f85df8)

2023-11-02 13:32 UTC, asmecher commented
@ajnyga, could you have a look over this one? Thanks!

2023-11-02 14:47 UTC, asmecher commented
@ajnyga, ah, you are correct :) Never mind, I'll have a look.

2023-11-02 14:58 UTC, asmecher requested changes
Thanks, @MrRob100, I've added some review comments!

2023-11-02 14:58 UTC, asmecher commented on ControlPublicFilesPlugin.inc.php
> +						$ext = pathinfo($temporaryFile->original_file_name, PATHINFO_EXTENSION);
@MrRob100, the original (client-side) filename shouldn't be considered trustworthy; is it possible that this could be abused to get a file past the checks?

2023-11-02 14:58 UTC, asmecher commented on ControlPublicFilesPlugin.inc.php
> +				$temporaryFile = $temporaryFileDao->retrieve(
Rather than coding SQL here, I think it would be much better to add a new function to `TemporaryFileDAO` to get temporary files by user ID. True that it'll only be available starting with the next `stable-3_3_0` release, but we can indicate that in the plugin gallery compatibility.

2023-11-02 14:58 UTC, asmecher commented on ControlPublicFilesPlugin.inc.php
> +						error_log('unable to lookup filetype: ' . $allowedFileType);
Is this necessary? If so, better to add more context about where the message is coming from.

2023-11-02 14:58 UTC, asmecher commented on ControlPublicFilesPlugin.inc.php
> +					$temporaryFileDao->deleteByUserId($request->getUser()->getId());
Better to use `deleteTemporaryFileById`, rather than deleting all temporary files for the user.

2023-11-08 17:14 UTC, MrRob100 commented on ControlPublicFilesPlugin.inc.php
> +				$temporaryFile = $temporaryFileDao->retrieve(
@asmecher The problem here is that in the hook I am using, I am unable to retrieve the temporary file id as it is not in the session yet `lastval is not yet defined in this session` I still want to perform the logic in this hook as I can access the form like this `$form = $params[0];` to be able to add the validation error message. Let me know if you have any ideas about how to get around this

2023-11-21 21:12 UTC, asmecher commented on ControlPublicFilesPlugin.inc.php
> +				$temporaryFile = $temporaryFileDao->retrieve(
Thanks, that looks good! I've taken the liberty of porting that function forward to `stable-3_4_0` and `main`; they'll be available in OJS/OMP/OPS starting with 3.3.0-17 and 3.4.0-5.

2023-11-21 21:14 UTC, asmecher commented
@MrRob100, with apologies for the delay -- now that https://github.com/pkp/controlPublicFiles/pull/14#discussion_r1387987154 is resolved, are the changes here ready for a last look?

2023-11-23 22:32 UTC, MrRob100 commented
> @MrRob100, with apologies for the delay -- now that [#14 (comment)](https://github.com/pkp/controlPublicFiles/pull/14#discussion_r1387987154) is resolved, are the changes here ready for a last look?

No problem. Yes It's ready

2023-11-23 22:51 UTC, merged

2023-11-23 22:52 UTC, asmecher commented
Thanks, @MrRob100! Could you forward-port this to 3.4.0 and open a PR for that against `main`? (We don't distinguish plugin `stable-3_4_0` from `main` until there's a reason, and that's generally after 3.5.0 gets released.)

2023-12-06 22:54 UTC, MrRob100 commented
> Thanks, @MrRob100! Could you forward-port this to 3.4.0 and open a PR for that against `main`? (We don't distinguish plugin `stable-3_4_0` from `main` until there's a reason, and that's generally after 3.5.0 gets released.)

Here it is. https://github.com/pkp/controlPublicFiles/pull/16 

When will the next release of 3.3 be cut? that will have the method `getTemporaryFilesByUserId` added to `TemporaryFileDAO`

2023-12-13 23:06 UTC, asmecher commented
Thanks, @MrRob100, merged!

The next cut of 3.3.0-x is not yet scheduled, but will almost certainly be Q1 2024. Watch the #development Mattermost channel for it to get scheduled, and feel free to nudge me if you'd like to know whether there's news on that front.