Check if disableRoles are null
pkp/controlPublicFiles pull request #8
Opened 2022-10-14 14:52 UTC by withanage

### Issue

- https://github.com/pkp/controlPublicFiles/issues/7

2022-10-14 15:22 UTC, asmecher requested changes

2022-10-14 15:22 UTC, asmecher commented on templates/settings.tpl
> +					{if in_array($roleId, $disableRoles)}
Should be:
```smarty
{if $disableRoles && in_array($roleId, $disableRoles))}
```
...rather than nested `{if}` statements. Otherwise a leftover value of `$checked` might get used from a previous template.

2022-10-14 16:05 UTC, withanage commented on templates/settings.tpl
> +					{if in_array($roleId, $disableRoles)}
Thanks @asmecher 

changed the if statement to reflect the changes

2022-10-14 16:06 UTC, merged

2022-10-14 16:07 UTC, asmecher commented
Merged, thanks!

2023-11-16 15:54 UTC, asmecher commented
Thanks for the reminder -- I just released a new package that includes the commit.